### ISSUE TITLE
Internal server error when opening FxA Email Preferences page using a Mozilla account

### ISSUE THREAD

**Issue by vasilicatamas** [mozmeao/basket#377]
**Build:**
Prod [Train 1.150.4]

**Affected platforms:**
Windows 10 64-bit
Android 9 

**Steps to reproduce:**
1.Launch Firefox and login into fxa using a Mozilla account.
2.Go to https://accounts.firefox.com/settings 
3.Click on “Email preferences” from the bottom of the page.

**Expected results:**
Email preferences page is successfully displayed.

 **Actual Results:**
“500 - Internal Server Error - Basket” is returned.

**Notes:**
- This issue reproduces only using a Mozilla account.
- Email preferences page is displayed when connecting with a different domain than “Mozilla” but the subscription changes are not saved.
![500error](https://user-images.githubusercontent.com/18114210/69238763-6deb5180-0ba1-11ea-9164-452521046ad0.gif)

**Comment by pmac** [comment]
I see errors in Sentry for this, but I'm having a hard time tracking down the problem. The errors are `ClientError('Unknown code')`, which seem to be coming from the PyFxA calls to `oauth.trade_code()`. This should be caught in an exception handler in basket and the user should be redirected to a page that indicates that there's been an error. Still investigating.

I have not reproduced this error however. I did sign in with both a mozilla.com email and a different domain, and both worked as expected. Is there any indication of errors with these codes on the FxA side? Maybe @shane-tomlinson can help us there?

**Comment by shane-tomlinson** [comment]
Strange, it looks like there were only 4 requests with "unknown code" yesterday, all from different IP addresses. The codes are not logged, so I am unable to check whether they are well formed or not.

**Comment by vasilicatamas** [comment]
I constantly receive this error for one FxA account created using my Mozilla email address https://basket.mozilla.org/fxa/callback/?code=2f032e9d726b36507e38b1be96cbac82a9afb54862f9fedb854323ec0417ff7f&state=d23bc9d984ec3109a0bd5bdfe34c02fe&action=signin

**Comment by pmac** [comment]
So weird. I can't yet figure out why, even if the code was invalid, you get a 500 error instead of a redirect to the error page. The code is catching that exception ¯\_(ツ)_/¯

**Comment by pmac** [comment]
Ah! Found it. It wasn't the `unknown code` error, it was that you apparently have more than one record in Salesforce for your email. I see the email from the gif in a `SalesforceMoreThanOneRecord` error. This is not being caught and is resulting in the 500. Unfortunately I'm not sure how to resolve this other than sending this kind of error to the error page, but it would likely never work for this email without manual action. It's nearly impossible to determine which record to use of the multiple returned...

**Comment by pmac** [comment]
Maybe you have some ideas how best to deal with this @andrewmozilla ?

**Comment by pmac** [comment]
I filed a PR that will redirect users with these errors to a nice error page instead of the 500 error, but this doesn't address the question of what to do about users with duplicate records.

**Comment by mirunacurtean** [comment]
This started occurring in production for accounts like mcurtean+11@mozilla.com. 
![Email Preferences 500 error](https://user-images.githubusercontent.com/53306802/74656920-d5606f80-5197-11ea-9454-f435a2dc692d.gif)

In stage the user is redirected to a Manage your Newsletter Subscriptions page however no email link is received after inputting the requested address. 
![Email prefernces link expired](https://user-images.githubusercontent.com/53306802/74657001-0345b400-5198-11ea-938c-2fcde014fecd.PNG)

I've been using variations of the original mcurtean@mozilla.com account for testing purposes so perhaps this is something that occurs after a while and cannot be reproduced that easily by less stressed accounts.

**Comment by pmac** [comment]
I think it's for all accounts right now. Basket's access to Salesforce has been paused due to an excess of API calls. Unfortunately Salesforce does not care about their users and cuts off our access after we use a certain number of API calls in a 24h period. When things get really busy sometimes we can exceed that. Should be resolved today or tomorrow.

**Comment by mirunacurtean** [comment]
Indeed, thanks for letting us know. I can confirm on both stage and production that the Manage your email Preferences page is now accessible through the Manage Acoount> Email Preferences link.

**Comment by vasilicatamas** [comment]
This issue is still reproducible in FxA Prod 158 Train:

![Screenshot_20](https://user-images.githubusercontent.com/18114210/74839588-2c984880-532e-11ea-8b46-be95b78fa1bb.png)

**Comment by pmac** [comment]
Yup. Still having Salesforce API issues. Thanks.
